version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - #ID=$aws_account_id
      - REPOSITORY_URI=$ecr_uri
      #- aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Building Docker images with Docker Compose...
      - docker-compose -f ./docker-compose.yaml build
      #- aws ecr create-repository --repository-name demotest/service1 --region ap-northeast-2 
      #- aws ecr create-repository --repository-name demotest/service2 --region ap-northeast-2 

  post_build:
    commands:
      - echo Tagging and pushing Docker images to ECR..
      - docker tag my-service1:latest $REPOSITORY_URI:latest1
      - docker tag my-service2:latest $REPOSITORY_URI:latest2
      - docker push $REPOSITORY_URI:latest1
      - docker push $REPOSITORY_URI:latest2
      
      - >
        container1_name="container1"
        container2_name="container2"
        image1_tag="latest1"
        image2_tag="latest2"
        
        image_definitions=(
          "{\"name\":\"demotest1\",\"imageUri\":\"$REPOSITORY_URI:$image1_tag\"}"
          "{\"name\":\"demotest2\",\"imageUri\":\"$REPOSITORY_URI:$image2_tag\"}"
        )
        
        image_definitions_json="[$(IFS=,; echo "${image_definitions[*]}")]"
        
        echo "$image_definitions_json" > imagedefinitions.json


      #- printf '[{"name":"'$ecs_container_name'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

