version: '3'
services:
  airflow:
    platform: linux/amd64
    build:
      context: ./airflow
      dockerfile: Dockerfile-airflow
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=your_database_connection_string
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    image: airflow:latest

  flask:
    platform: linux/amd64
    build:
      context: ./flask
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    image: flask:latest
